### ISSUE TITLE
Decidir si usar prepared statement o dictionary

### ISSUE THREAD

**Issue by wgm1001** [wgm1001/Trabajo-de-Fin-de-Grado-Plataforma-de-text-mining-sobre-repositorios#19]
Hay un problema con los cursores y es que no te permite que tengan a la vez la propiedad de prepared y la de dictionary, hay que decidir que preferimos, adapralos para que funcionen con prepared sacrificando un poco la facilidad de lectura de la clase o dejarlo así sacrificando la eficiencia.

**Comment by clopezno** [comment]
Creo que es interesante que comentes  el contexto funcional te puede ayudar a tomar la elección.  Es decir. conocer los tipos de _statement_, número de veces que se van a utilizar por la aplicación, número de registros de las tablas...

Con ese contexto definido, indicaría las ventajas e inconvenientes de cada alternativa. Las pruebas pueden ayudarte a apoyar empíricamente tu decisión.

**Comment by wgm1001** [comment]
finalmente lo realizaré con prepared ya que la eficiencia me parecer más relevante
